# https://travis-ci.org/
language: node_js
node_js:
  - '4'
script: 'npm run verify:travis'
install:
  - 'travis_retry npm install'
addons:
  firefox: 'latest'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script: "node_modules/.bin/testem launchers"
