# https://travis-ci.org/
language: node_js
node_js:
  - '4'
addons:
  firefox: 'latest'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- 'travis_retry npm install'
before_script:
- "npm run test -- --file testem.travis.js launchers"
script: 'npm run verify:travis'
