# http://www.appveyor.com/docs/appveyor-yml

# init
clone_depth: 20

environment:
  matrix:
  - nodejs_version: 4

# install
install:
- choco install firefox
- choco install googlechrome
- ps: . .\Execute-With-Retry
- ps: Execute-With-Retry { Install-Product node $env:nodejs_version }
- node --version
- npm --version
- windows_retry npm install

# build
build: off

# test
before_test:
- "npm run test -- --file testem.appveyor.js launchers"
test_script:
- npm run verify:appveyor

# deploy
deploy: off

# notify
notifications:
- provider: Email
  to:
  - o.gata.ken@gmail.com
  on_build_status_changed: true
